version: '3.4'

services:
  notebook:
    image: mattjtodd/docker-airflow
    build: ./
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
      - 8080:8080
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - $PWD/dags:/home/jovyan/airflow/dags
      - $PWD/books:/home/jovyan/books

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
