version: '3.4'

services:
  notebook:
    build: .
    image: mattjtodd/docker-airflow
    build: ./
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
      - 8080:8080
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - $PWD/work:/home/jovyan

volumes:
  work:
