version: '3.4'

services:
  notebook:
    image: mattjtodd/docker-jupyter-jdk:11
    build: ./
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8889:8888
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - $PWD/work:/home/jovyan/work

volumes:
  work:
